create table if not exists public.fmg_reality_check_responses (
  id bigint generated by default as identity primary key,
  response_id text not null unique,
  assessment_version text not null,
  submitted_at timestamptz not null default now(),
  research_consent boolean not null default false,
  answers jsonb not null default '{}'::jsonb,
  derived jsonb not null default '{}'::jsonb,
  contact jsonb not null default '{}'::jsonb,
  source jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists fmg_reality_check_responses_submitted_at_idx
  on public.fmg_reality_check_responses (submitted_at desc);

create index if not exists fmg_reality_check_responses_research_fit_idx
  on public.fmg_reality_check_responses ((derived->>'research_fit'));

create index if not exists fmg_reality_check_responses_interview_opt_in_idx
  on public.fmg_reality_check_responses (((contact->>'interview_opt_in')::boolean));

alter table public.fmg_reality_check_responses enable row level security;

-- Browser roles intentionally have no direct access. The Vercel serverless
-- endpoint writes with the server-only service role or secret key.
revoke all on table public.fmg_reality_check_responses from anon, authenticated;
grant select, insert on table public.fmg_reality_check_responses to service_role;
grant usage, select on sequence public.fmg_reality_check_responses_id_seq to service_role;

-- No public RLS policy is intentionally created.
-- Keep the server key out of browser code and public environment variables.
